blueprint:
  name: Zone Notification Extended
   
  source_url: "https://github.com/andrewdolphin/Homeassistant_Blueprints/Blueprints/ad_zone_notifications.yaml"
  domain: automation
  homeassistant:
    min_version: 2023.8.0

  input:
    persons:
      name: 👥 Persons
      description: > 
        People who trigger the automation when they enter or leave the specified zones.
      selector:
        entity:
          filter:
            domain: person
          multiple: true

    zones:
      name: 🌐 Zones
      description: > 
        Define the zones you want to observe for arriving and leaving. Leave the field blank to select all your defined zones.
        If your define no *Leaving Zones* all zone you define here will taken for arriving and leaving notifications / actions.
      default: []
      selector:
        entity:
          filter:
            domain: zone
          multiple: true

    zones_leaving:
      name: 🌐 Leaving Zones
      description: >
        `optional`


        Zones specified here are used exclusively for leaving notifications / actions.
      default: []
      selector:
        entity:
          filter:
            domain: zone
          multiple: true

    notify_device:
      name: 📱 Device to notify
      description: >
        `optional`


        Device that is to receive the notifications.
      default:
      selector:
        device:
          filter:
            integration: mobile_app

    title_arriving:
      name: "📩 Notification Arriving Title"
      description: >
        Title for entering notifications.
      default: "{{ person }} arrives"

    message_arriving:
      name: "📨 Notification Arriving Message"
      description: >
        Notification message when someone enters a zone.
      default: "{{ person }} arrives at {{ zone }}."

    is_arriving_notification_enabled:
      name: "🎚️ Enable Arriving Notification"
      description: >
        If *on* notification will be sent when a person enters a zone.
      default: true
      selector:
        boolean:

    title_leaving:
      name: "📩 Notification Leaving Title"
      description: >
        Notification title when someone is leaving a zone.
      default: "{{ person }} leaves"

    message_leaving:
      name: "📨 Notification Leaving Message"
      description: >
        Notification message when someone is leaving a zone.
      default: "{{ person }} leaves {{ zone }}."

    is_leaving_notification_enabled:
      name: "🎚️ Enable Leaving Notification"
      description: >
        If *on* notification will send when a person leaves a zone.
      default: true
      selector:
        boolean:

    custom_conditions:
      name: "❌ Custom Conditions"
      description: >
        `optional`


        Custom conditions when the automation action part should be triggered."
      default: []
      selector:
        condition:

    custom_conditions_arriving:
      name: "❌ Conditions Arriving"
      description: >
        `optional`


        Custom conditions only for arriving notifications / actions.
      default: []
      selector:
        condition:

    custom_conditions_leaving:
      name: "❌ Conditions Leaving"
      description: >
        `optional`

      
        Custom conditions when notifications / actions for leaving are active.
      default: []
      selector:
        condition:


variables:
  zone_inputs: !input zones
  zones: >
    {% if zone_inputs | count > 0 %}
      {{ zone_inputs }}
    {% else %}
      {{ integration_entities('zone') | default([]) }}
    {% endif %}

  home_zone_name: "{{ 'home' | lower }}"
  home_zone: "{{ 'zone.home' | lower }}"
  not_home: "{{ 'not_home' | lower }}"
  zone_names: |
    {% set friendly = namespace(name=[]) %}
    {% for zone in zones %}
      {% set new_zone = state_attr(zone,'friendly_name') %}
      {% if home_zone == zone %}
        {% set friendly.name = friendly.name + [home_zone_name] %}
      {% endif %}
      {% set friendly.name = friendly.name + [new_zone.strip()] %}
    {% endfor %}

    {{ friendly.name }}

  zones_leaving: !input zones_leaving
  zones_leaving_names: |
    {% set friendly = namespace(name=[]) %}
    {% for zone in zones_leaving %}
      {% set new_zone = state_attr(zone,'friendly_name') %}
      {% if home_zone == zone %}
        {% set friendly.name = friendly.name + [home_zone_name] %}
      {% endif %}
      {% set friendly.name = friendly.name + [new_zone.strip()] %}
    {% endfor %}

    {{ friendly.name }}

  notify_device: !input notify_device
  notify_service: |
    notify.mobile_app_{{ device_attr(notify_device, "name") | slugify }}

  is_arriving_notification_enabled: !input is_arriving_notification_enabled
  is_leaving_notification_enabled: !input is_leaving_notification_enabled


trigger:
  platform: state
  entity_id: !input persons

condition:
  - condition: template
    value_template: "{{ trigger.to_state.state != trigger.from_state.state }}"

  - condition: or
    conditions:
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ (trigger.to_state.state != not_home and trigger.to_state.state in zone_names) or (trigger.from_state.state != not_home and trigger.from_state.state in zone_names) }}"
          - alias: "no leaving zones defined"
            condition: template
            value_template: "{{  zones_leaving | count == 0 }}"
      - condition: and
        conditions:
          - condition: template
            value_template: "{{ (trigger.to_state.state != not_home and trigger.to_state.state in zone_names) or (trigger.from_state.state != not_home and trigger.from_state.state in zones_leaving_names) }}"
          - alias: "no leaving zones defined"
            condition: template
            value_template: "{{  zones_leaving | count > 0 }}"
  - condition: and
    conditions: !input custom_conditions

action:
  - variables:
      person: "{{ state_attr(trigger.entity_id,'friendly_name') }}"
      zone_from: "{{ iif(trigger.from_state.state | lower != not_home,iif(trigger.from_state.state | lower == home_zone_name,state_attr(home_zone,'friendly_name'),trigger.from_state.state),not_home) }}"
      zone_to: "{{ iif(trigger.to_state.state | lower != not_home,iif(trigger.to_state.state | lower == home_zone_name,state_attr(home_zone,'friendly_name'),trigger.to_state.state),not_home) }}"
      zone_names_arriving: "{{ zone_names }}"
      zone_names_leaving: "{{ iif(zones_leaving | count == 0, zone_names, zones_leaving_names) }}"

  - if:
      - condition: template
        value_template: "{{ zone_from in zone_names_leaving }}"
      - condition: template
        value_template: "{{ is_leaving_notification_enabled }}"
      - condition: template
        value_template: "{{ notify_service != none and notify_service != '' }}"
      - condition: and
        conditions: !input custom_conditions_leaving
    then:
      - delay:
          seconds: 30
      - if:
          - condition: template
            value_template: "{{ states(trigger.entity_id) == zone_from }}"
        then:
          - stop: "Person returned within 30 seconds; suppressing departure notification."
      - variables:
          zone: "{{ zone_from }}"
      - service: "{{ notify_service }}"
        data:
          title: !input title_leaving
          message: !input message_leaving
          data:
            ttl: 0
            priority: high
            image: "/local/{{ person }}.png"
  - if:
      - condition: template
        value_template: "{{ zone_to in zone_names_arriving }}"
      - condition: template
        value_template: "{{ is_arriving_notification_enabled }}"
      - condition: template
        value_template: "{{ notify_service != none and notify_service != '' }}"
      - condition: and
        conditions: !input custom_conditions_arriving
    then:
      - if:
          - condition: template
        # Check if they were arriving from 'not_home' and if that 'not_home' period was < 30s
            value_template: >
              {{ trigger.from_state.state == 'not_home' and 
                 (as_timestamp(now()) - as_timestamp(trigger.from_state.last_changed)) < 30 }}
        then:
          - stop: "Person was away for less than 30 seconds; suppressing arrival notification."
      - variables:
          zone: "{{ zone_to }}"
      - service: "{{ notify_service }}"
        data:
          title: !input title_arriving
          message: !input message_arriving
          data:
            ttl: 0
            priority: high
            image: "/local/{{ person }}.png"
mode: parallel
